server:
  port: 8080
spring:
  application:
    name: masterslave
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
    master:
      url: jdbc:mysql://IP:PORT/DATABASE_NAME?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: USERNAME
      password: PASSWORD
    slave1:
      url: jdbc:mysql://IP:PORT/DATABASE_NAME?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: USERNAME
      password: PASSWORD
    slave2:
      url: jdbc:mysql://IP:PORT/DATABASE_NAME?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: USERNAME
      password: PASSWORD


mybatis-plus:
  mapper-locations: "classpath*:/mapper/*.xml"
